### ISSUE TITLE
Device Discovery

### ISSUE THREAD

**Issue by alexrierra** [Laex/Delphi-ONVIF#8]
On Windows 10, the demo is not able to discover my IP cameras. 
I run ONVIF Device Manager (also open-source app) and then closeit, your demo starts working fine: it founds all cameras.  
After some period of time, your demo stops founding the cameras again.
I don't know what exactly happens, it looks like ONVIF Device Manager "temporary opens the doors for ONVIF discovery".
What could be the problem?
Thanks.

**Comment by Laex** [comment]
Error could not be reproduced.
Cameras are detected on Windows 10.
If there are new assumptions or information, we will continue ...
